# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: "Armin Saadat"
#title: Blah
email: arminsdt@ece.ubc.ca

# Social links
# twitter_username: facespics
github_username:  armin-saadat

# googlescholar_username: Gv9ET40AAAAJ

# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: armin-saadat
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/personal_photo.png
about_content: | # this will include new lines to allow paragraphs
  **resume: [PDF](https://armin-saadat.github.io/files/resume.pdf)**

  
  Currently, I am a M.Sc. student at **University of British Columbia (UBC)** conducting research on medical imaging under the supervision of **Dr. Purang Abolmaesumi**. 
  I received my B.Sc. from **Sharif University of Technology**, where I was working on computer vision with an emphasis on developing deep learning methods for medical applications. 
  Moreover, in July 2021, I received a prestigious research internship from the Visual Intelligence for Transportation, **Swiss Federal Institute of Technology Lausanne (EPFL)**.
  This internship allowed me to work with **Prof. Alahi** on the challenging topic of Pose & Trajectory Forecasting for Autonomous Driving.
  
  My research interests include **Applied Machine Learning**, **Explainable AI**, **ML in Healthcare**, **Autonomous Driving**. 
# Projects Section
# projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:  
   - Playing Basketball (captain of the college team)
   - Observational Astronomy
   - Mountain Climbing & Camping

# Footer
footer_show_references: true

# Build settings
remote_theme: armin-saadat/armin-saadat.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
