# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: "Armin Saadat"
#title: Blah
email: armin2saadat@gmail.com
skype: live:946c38eae8688af6

# Social links
# twitter_username: facespics
github_username:  armin-saadat

# googlescholar_username: Gv9ET40AAAAJ

# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: armin-saadat
skype_username: live:946c38eae8688af6
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/personal_photo.png
about_content: | # this will include new lines to allow paragraphs
  **CV: [PDF](https://armin-saadat.github.io/files/CV.pdf)**

  
  Currently, I am a B.Sc. senior student majoring in Computer Engineering at the **Sharif University of Technology (SUT)**. 
  In November 2019, I joined the Robust & Interpretable Machine Learning Lab (RIML) in SUT as a **research assistant**. 
  Since then, I have been researching Computer Vision with an emphasis on developing deep learning methods for medical applications. 
  In July 2021, I received a prestigious research internship from the Visual Intelligence for Transportation (VITA Lab), **Swiss Federal Institute of Technology Lausanne (EPFL)**.
  This internship allowed me to work with **Prof. Alahi**, one of the most prominent professors in transportation and socially-aware artificial intelligence, on the challenging topic of Pose & Trajectory Forecasting.
  My research interests include **Computer Vision**, **Medical Imaging**, **Autonomous Driving**, and **Machine Learning**. 
# Projects Section
# projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Science and Technology, some of my other hobbies are:  
   - Playing Basketball (captain of the college team)
   - Observational Astronomy
   - Mountain Climbing & Camping

# Footer
footer_show_references: true

# Build settings
remote_theme: armin-saadat/armin-saadat.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
